### ISSUE TITLE
RFC - disable flash in AJAX header by default, and wait for specific request header

### ISSUE THREAD

**Issue by Ali1** [dereuromark/cakephp-flash#7]
I have been thinking about it after I once had an issue with lost Flash messages. Turned out they were occurring due to AJAX requests being made around the same time as Flash messages were being generated (e.g. ajax request to submit form, which if successfully causes a browser redirect). And now that there is new major version, putting this question to you.

My application does have specific uses for the ajax flash header feature - but these are very intentionally, with a client side handler for the Flash header waiting to be called. Most AJAX requests will not be ready to handle flash messages - which will subsequently be lost.

It seems more natural that the default behaviour is not to have a Flash header unless one is specifically requested.

For example the feature should by default only work if there is a X-Get-Flash: yes header in the request.

I currently have this conditional in my AppController.php to avoid problems.
```
        if (!$this->request->getHeader('Get-Flash')) {
            $this->Flash->setConfig('headerKey', ''); // setting only relevant for XHR requests. We don't want to lose flash messages on these except if specifically requested with Get-Flash - used to have problems e.g. if changing appointment, the pusher update comes before the redirect so flash message is lost
        }
```

**Comment by dereuromark** [comment]
Do you want to make a PR with the suggested changes?

**Comment by dereuromark** [comment]
Well, thinking about this some more.
If you use Flash together with Ajax plugin and auto-AJAX of normal actions, then you would want those to be rendered out (or at least silently consumed/removed) since they are produced by this action.
Having them around for the next non-AJAX request would also be weird.

This said, it leaves now a general problem open: The AJAX vs non-AJAX race condition of consuing each others messages and creating message side effects.

The only solution here would be have a different stack for AJAX requests alltogether.
And ones that are not stored in the session (to avoid polluting the normal actions).

What do you think?

**Comment by Ali1** [comment]
If AJAX actions are returning a HTML template which displays Flash messages, they would be consumed correctly.

And if you want to silently remove Flash actions, they should not be generated in the Controller in the first place conditional upon `request->is('ajax')`

**Comment by dereuromark** [comment]
That is true :)
I am just wondering if we could keep the config to allow people to enable "always" if needed/wanted.

**Comment by Ali1** [comment]
I wondered too but I think on balance, very few would find it useful.

AJAX-only applications that have a common response handler which handles
will guarantee processing every flash messages, will also probably have a
common request function that can easily add a Get Flash header (same
difficulty as setting The component config)
-- 
Sent from my iPhone
